Для вывода результата функции добавьте "df" в конце желаемого блока

In [4]:
import pandas as pd
id_SubFed = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
ulsk = [
    'Ульяновская область'
]

In [15]:
id_SubFed = ['Республика Башкортостан',
             'Республика Марий Эл',
             'Республика Мордовия',
             'Республика Татарстан',
             'Удмуртская Республика',
             'Чувашская Республика',
             'Пермский край',
             'Кировская область',
             'Нижегородская область',
             'Оренбургская область',
             'Пензенская область',
             'Самарская область',
             'Саратовская область',
             'Ульяновская область']
df = pd.DataFrame(id_SubFed, columns=['name'])
df = df.set_index('id')
df.to_csv('CSVs/SubFed', sep=';')

KeyError: "None of ['id'] are in the columns"

In [9]:
#Amount_GS
group = [
    'Численность государственных должностей субъекта Российской Федерации',
    'Численность должностей государственной гражданской службы',
    'Численность должностей, не отнесенных к должностям государственной гражданской службы'
]
status = [
    'Всего',
    'замещено',
    'количество лиц, находящихся в отпуске по уходу за ребенком'
]

df = pd.read_excel('data_xlsx/2020_full.xlsx', sheet_name='1.1. Кол-во ГС', header = None)
df = df.iloc[6:20, 6:18]
df = df.drop([9,13,17], axis = 1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, group, status], names = ['id_SubFed', 'group', 'status'])
df = df.set_axis(m_id, axis = 0)
df = df.rename(columns={0:'amount'})
df.insert(0, 'year', 2021)
df

                                                                                                                 year  \
id_SubFed group                                              status
0         Численность государственных должностей субъекта... Всего                                               2021
                                                             замещено                                            2021
                                                             количество лиц, находящихся в отпуске по уходу ...  2021
          Численность должностей государственной гражданс... Всего                                               2021
                                                             замещено                                            2021
...                                                                                                               ...
13        Численность должностей государственной гражданс... замещено                                            2021
                                                             количество лиц, находящихся в отпуске по уходу ...  2021
          Численность должностей, не отнесенных к должнос... Всего                                               2021
                                                             замещено                                            2021
                                                             количество лиц, находящихся в отпуске по уходу ...  2021

                                                                                                                amount
id_SubFed group                                              status
0         Численность государственных должностей субъекта... Всего                                                  71
                                                             замещено                                               69
                                                             количество лиц, находящихся в отпуске по уходу ...      0
          Численность должностей государственной гражданс... Всего                                                5075
                                                             замещено                                             4738
...                                                                                                                ...
13        Численность должностей государственной гражданс... замещено                                             1317
                                                             количество лиц, находящихся в отпуске по уходу ...    132
          Численность должностей, не отнесенных к должнос... Всего                                                 233
                                                             замещено                                              223
                                                             количество лиц, находящихся в отпуске по уходу ...     17

[126 rows x 2 columns]

In [42]:
#Amount_MS
group = [
    'Численность должностей муниципальной службы',
    'Численность должностей, не отнесенных к должностям муниципальной службы'
]
status = [
    'Всего',
    'замещено',
    'количество лиц, находящихся в отпуске по уходу за ребенком'
]

df = pd.read_excel('2021x.xlsx', sheet_name='1.2. Кол-во МС', header = None)
df = df.iloc[6:20, 6:14]
df = df.drop([9,13], axis = 1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, group, status], names = ['id_SubFed', 'group', 'status'])
df = df.set_axis(m_id, axis = 0)
df = df.rename(columns={0:'amount'})
df.insert(0, 'year', 2021)

In [43]:
#Gender_GS_MS
gender = [
    'мужчины',
    'женщины'
]

df = pd.read_excel('2021x.xlsx', sheet_name='2.1. Гендерный ГС', header = None)
df = df.iloc[4:18, 2:6]
df = df.drop([3,5], axis = 1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, gender], names = ['id_SubFed', 'gender'])
df = df.set_axis(m_id, axis = 0)
df = df.rename(columns={0:'amount'})
df.insert(0, 'year', 2021)

In [44]:
#Age_GS_MS
category = [
    'до 30 лет',
    'от 31 до 40 лет',
    'от 41 до 50 лет',
    'от 51 до 60 лет',
    'возраст старше 61 года',
    'средний возраст служащих'
]

df = pd.read_excel('2021x.xlsx', sheet_name='3.2. Возраст МС', header = None)
df = df.iloc[4:18, 2:13]
df = df.drop([3,5,7,9,11], axis = 1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, category], names = ['id_SubFed', 'category'])
df = df.set_axis(m_id, axis = 0)
df = df.rename(columns={0:'amount'})
df.insert(0, 'year', 2021)

In [2]:
#EducationLevel_GS_MS
educ_lvl = [
    'бакалавриат',
    'специалитет',
    'магистратура',
    'среднее профессиональное'
]

df = pd.read_excel('data_xlsx/2023_full.xlsx', sheet_name='4.1. Образовательный уровень ГС', header = None)
df = df.iloc[6:20, 4:21]
df = df.drop([5,7,9,10,11,12,13,14,15,16,17,18,19], axis = 1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, educ_lvl], names = ['id_SubFed', 'educ_lvl'])
df = df.set_axis(m_id, axis = 0)
df = df.rename(columns={0:'amount'})
df.insert(0, 'year', 2021)
df

                                    year amount
id_SubFed educ_lvl
0         бакалавриат               2021    687
          специалитет               2021   3516
          магистратура              2021    353
          среднее профессиональное  2021    274
1         бакалавриат               2021     86
          специалитет               2021   1019
          магистратура              2021     99
          среднее профессиональное  2021      0
2         бакалавриат               2021     73
          специалитет               2021    965
          магистратура              2021     79
          среднее профессиональное  2021     28
3         бакалавриат               2021    729
          специалитет               2021   4190
          магистратура              2021    169
          среднее профессиональное  2021    187
4         бакалавриат               2021    237
          специалитет               2021   1241
          магистратура              2021    145
          среднее профессиональное  2021     60
5         бакалавриат               2021    206
          специалитет               2021    992
          магистратура              2021     80
          среднее профессиональное  2021     16
6         бакалавриат               2021    613
          специалитет               2021   2305
          магистратура              2021    135
          среднее профессиональное  2021    138
7         бакалавриат               2021    207
          специалитет               2021   1509
          магистратура              2021    124
          среднее профессиональное  2021      9
8         бакалавриат               2021    439
          специалитет               2021   3041
          магистратура              2021    293
          среднее профессиональное  2021     20
9         бакалавриат               2021    226
          специалитет               2021   1598
          магистратура              2021    182
          среднее профессиональное  2021     46
10        бакалавриат               2021    200
          специалитет               2021   1298
          магистратура              2021    121
          среднее профессиональное  2021     13
11        бакалавриат               2021    327
          специалитет               2021   3193
          магистратура              2021    234
          среднее профессиональное  2021    208
12        бакалавриат               2021    300
          специалитет               2021   1918
          магистратура              2021    252
          среднее профессиональное  2021     11
13        бакалавриат               2021    128
          специалитет               2021   1139
          магистратура              2021     77
          среднее профессиональное  2021     10

In [3]:
#Educ_spec_GS_MS
speciality = [
    'менеджер ГМУ',
    'экономист, финансист',
    'юрист',
    'инженер',
    'иная специальность'
]

df = pd.read_excel('data_xlsx/2023_full.xlsx', sheet_name='4.1. Образовательный уровень ГС', header = None)
df = df.iloc[6:20, 10:20]
df = df.drop([11,13,15,17,19], axis = 1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, speciality], names = ['id_SubFed', 'speciality'])
df = df.set_axis(m_id, axis = 0)
df = df.rename(columns={0:'amount'})
df.insert(0, 'year', 2021)
df

                                year amount
id_SubFed speciality
0         менеджер ГМУ          2021    337
          экономист, финансист  2021   1168
          юрист                 2021   1462
          инженер               2021    642
          иная специальность    2021    947
...                              ...    ...
13        менеджер ГМУ          2021     86
          экономист, финансист  2021    372
          юрист                 2021    415
          инженер               2021    120
          иная специальность    2021    351

[70 rows x 2 columns]

In [47]:
#AcademicDegree_GS_MS
degree = [
    'Два и более высших образования',
    'Кандидаты наук',
    'Доктора наук'
]

df = pd.read_excel('2021x.xlsx', sheet_name='5.1. Ученая степень ГС', header = None)
df = df.iloc[4:18, 2:7]
df = df.drop([3,5], axis = 1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, degree], names = ['id_SubFed', 'degree'])
df = df.set_axis(m_id, axis = 0)
df = df.rename(columns={0:'amount'})
df.insert(0, 'year', 2021)

In [48]:
#Exp_GS_MS
category = [
    'до 1 года',
    'от 1 года до 5 лет',
    'от 5 до 10 лет',
    'от 10 до 15 лет',
    'свыше 15 лет'
]

df = pd.read_excel('2021x.xlsx', sheet_name='6.1. Стаж ГС', header = None)
df = df.iloc[4:18, 2:11]
df = df.drop([3,5,7,9], axis = 1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, category], names = ['id_SubFed', 'category'])
df = df.set_axis(m_id, axis = 0)
df = df.rename(columns={0:'amount'})
df.insert(0, 'year', 2021)

In [56]:
#Changeability_GS
category = [
    'Уволены на отчетную дату по инициативе служащего',
    'Уволены на отчетную дату по инициативе представителя нанимателя ',
    'Уволены на отчетную дату по истечению срока срочного служебного контракта',
    'Уволены на отчетную дату по иным основаниям ',
    'Количество служащих уволенных по достижению предельного возраста пребывания на службе',
    'Количество уволенных служащих пребывавших в должности менее 1 года',
    'Количество служащих уволенных в связи с сокращением штатной численности, преобразованием государственных органов',
    'Количество служащих предупрежденных о предстоящем возможном увольнении'
]

df = pd.read_excel('2021x.xlsx', sheet_name='7. Сменяемость ГС', header = None)
df = df.iloc[4:18, 4:16]
df = df.drop([5,7,9,11], axis = 1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, category], names = ['id_SubFed', 'category'])
df = df.set_axis(m_id, axis = 0)
df = df.rename(columns={0:'amount'})
df.insert(0, 'year', 2021)

In [60]:
#GosOrgAmount
category = [
    'Количество государственных органов на отчетную дату',
    'Количество государственных органов на последнюю дату отчета предыдущего года'
]

df = pd.read_excel('2021x.xlsx', sheet_name='8. Кол-во гос.органов', header = None)
df = df.iloc[5:19, 2:4]
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, category], names = ['id_SubFed', 'category'])
df = df.set_axis(m_id, axis = 0)
df = df.rename(columns={0:'amount'})
df.insert(0, 'year', 2021)

In [6]:
#Competition
category = [
    'Общее количество конкурсов',
    'Конкурсы, проводимые повторно',
    'Несостоявшиеся конкурсы',
    'Конкурсы, результаты которых были обжалованы',
    'Общее количество конкурсов на включение в кадровый резерв'
]

df = pd.read_excel('data_xlsx/2023_full.xlsx', sheet_name='9. Конкурсы', header=None)
df = df.iloc[5:19, 2:10]
df = df.drop([4, 6, 8], axis=1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, category], names=['id_SubFed', 'category'])
df = df.set_axis(m_id, axis=0)
df = df.rename(columns={0: 'amount'})
df.insert(0, 'year', 2021)
df

                                                              year amount
id_SubFed category
0         Общее количество конкурсов                          2021     36
          Конкурсы, проводимые повторно                       2021      3
          Несостоявшиеся конкурсы                             2021     19
          Конкурсы, результаты которых были обжалованы        2021      0
          Общее количество конкурсов на включение в кадро...  2021     68
...                                                            ...    ...
13        Общее количество конкурсов                          2021    110
          Конкурсы, проводимые повторно                       2021     14
          Несостоявшиеся конкурсы                             2021     50
          Конкурсы, результаты которых были обжалованы        2021      0
          Общее количество конкурсов на включение в кадро...  2021     74

[70 rows x 2 columns]

In [83]:
#CitizenParticipation
category = [
    'подали документы на замещение вакантных должностей государственной службы',
    'в эл. виде подали документы на замещение вакантных должностей государственной службы',
    'подали документы на включение в кадровый резерв',
    'в эл. виде подали документы на включение в кадровый резерв',
    'количество лиц, не допущенных для участия в конкурсе',
    'количество лиц, не прошедших конкурсный отбор',
    'количество лиц, назначенных на вакантную должность по результатам конкурса',
    'количество лиц, включенных в кадровый резерв, по результатам конкурса на замещение',
    'количество лиц, включенных в кадровый резерв, по результатам конкурса на включение в кадровый резерв',
    'количество лиц, не участвовавших в конкурсе по причине признания конкурса несостоявшимся'
]

df = pd.read_excel('2021x.xlsx', sheet_name='10. Участие граждан', header=None)
df = df.iloc[6:20, 2:17]
df = df.drop([7, 9, 11, 13, 15], axis=1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, category], names=['id_SubFed', 'category'])
df = df.set_axis(m_id, axis=0)
df = df.rename(columns={0: 'amount'})
df.insert(0, 'year', 2021)

In [82]:
#Substitution
category = [
    'В возрасте до 30 лет',
    'С установлением испытательного срока',
    'Количество лиц, назначенных на должности по результатам конкурса',
    'Количество лиц, назначенных на должности в порядке должностного роста',
    'Без конкурса, по срочному служебному контракту',
    'Без конкурса, исполнение обязанностей по которым связано с государственной тайной',
    'Без конкурса, из кадрового резерва',
    'Без конкурса, по иным основаниям'
]

df = pd.read_excel('2021x.xlsx', sheet_name='11. Замещение', header=None)
df = df.iloc[7:21, 3:17]
df = df.drop([5,7,9,11,13,15], axis=1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, category], names=['id_SubFed', 'category'])
df = df.set_axis(m_id, axis=0)
df = df.rename(columns={0: 'amount'})
df.insert(0, 'year', 2021)

In [13]:
#Mentoring
category = [
    'впервые поступившие на гос. службу',
    'впервые поступившие на гос. службу, которым назначены наставники',
    'впервые назначенных на высшие и главные должности гос. службы',
    'впервые назначенных на высшие и главные должности гос. службы, которым назначены наставники',
    'иные случаи установления наставничества',
    'Назначенные наставники',
    'Назначенные наставники, которым произведена доплата'
]

df = pd.read_excel('data_xlsx/2023_full.xlsx', sheet_name='12. Наставничество', header=None)
df = df.iloc[7:21, 2:13]
df = df.drop([4,7,9,12], axis=1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, category], names=['id_SubFed', 'category'])
df = df.set_axis(m_id, axis=0)
df = df.rename(columns={0: 'amount'})
df.insert(0, 'year', 2021)
df

                                                              year amount
id_SubFed category
0         впервые поступившие на гос. службу                  2021    413
          впервые поступившие на гос. службу, которым наз...  2021    107
          впервые назначенных на высшие и главные должнос...  2021     37
          впервые назначенных на высшие и главные должнос...  2021      0
          иные случаи установления наставничества             2021     18
...                                                            ...    ...
13        впервые назначенных на высшие и главные должнос...  2021     39
          впервые назначенных на высшие и главные должнос...  2021     31
          иные случаи установления наставничества             2021     90
          Назначенные наставники                              2021    204
          Назначенные наставники, которым произведена доп...  2021    101

[98 rows x 2 columns]

In [14]:
#ReserveComposition
category = [
    'Количество государственных органов, сформировавших резерв',
    'граждан',
    'государственных служащих'
]

df = pd.read_excel('data_xlsx/2023_full.xlsx', sheet_name='13. Резерв', header=None)
df = df.iloc[6:20, 2:8]
df = df.drop([3,4,6], axis=1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, category], names=['id_SubFed', 'category'])
df = df.set_axis(m_id, axis=0)
df = df.rename(columns={0: 'amount'})
df.insert(0, 'year', 2021)
df

                                                              year amount
id_SubFed category
0         Количество государственных органов, сформировав...  2021     40
          граждан                                             2021    545
          государственных служащих                            2021   1160
1         Количество государственных органов, сформировав...  2021     24
          граждан                                             2021    126
          государственных служащих                            2021    299
2         Количество государственных органов, сформировав...  2021     21
          граждан                                             2021    150
          государственных служащих                            2021    198
3         Количество государственных органов, сформировав...  2021     41
          граждан                                             2021    651
          государственных служащих                            2021   1492
4         Количество государственных органов, сформировав...  2021     30
          граждан                                             2021    156
          государственных служащих                            2021    356
5         Количество государственных органов, сформировав...  2021     24
          граждан                                             2021    342
          государственных служащих                            2021    332
6         Количество государственных органов, сформировав...  2021     39
          граждан                                             2021   1680
          государственных служащих                            2021   2756
7         Количество государственных органов, сформировав...  2021     34
          граждан                                             2021    274
          государственных служащих                            2021    682
8         Количество государственных органов, сформировав...  2021     47
          граждан                                             2021    718
          государственных служащих                            2021   2505
9         Количество государственных органов, сформировав...  2021     33
          граждан                                             2021    274
          государственных служащих                            2021    331
10        Количество государственных органов, сформировав...  2021     24
          граждан                                             2021    102
          государственных служащих                            2021    288
11        Количество государственных органов, сформировав...  2021     27
          граждан                                             2021    392
          государственных служащих                            2021    784
12        Количество государственных органов, сформировав...  2021     26
          граждан                                             2021    144
          государственных служащих                            2021    310
13        Количество государственных органов, сформировав...  2021     24
          граждан                                             2021    146
          государственных служащих                            2021    404

In [112]:
#ReserveCause
cause = [
    'по результатам конкурса на включение в кадровый резерв',
    'по результатам конкурса на замещение вакантной должности',
    'по результатам аттестации',
    'в связи с сокращением должностей',
    'по основаниям, предусмотренным ч.1 ст. 39 Федерального закона 79-ФЗ'
]

df = pd.read_excel('2021x.xlsx', sheet_name='13. Резерв', header=None)
df = df.iloc[6:20, 9:18]
df = df.drop([10,12,14,16], axis=1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, cause], names=['id_SubFed', 'cause'])
df = df.set_axis(m_id, axis=0)
df = df.rename(columns={0: 'amount'})
df.insert(0, 'year', 2021)

In [13]:
#Attestation
result = [
    'соответствуют замещаемой должности',
    'соответствуют замещаемой должности и рекомендованы к включению в кадровый резерв',
    'соответствуют замещаемой должности при условии успешного получения дополнительного профессионального образования',
    'не соответствуют замещаемой должности'
]
period = [
    'АППГ',
    'с начала отчетного года'
]

df = pd.read_excel('data_xlsx/2022_full.xlsx', sheet_name='14. Аттестация', header=None)
df = df.iloc[6:20, 4:12]
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, result, period], names=['id_SubFed', 'result', 'period'])
df = df.set_axis(m_id, axis=0)
df = df.rename(columns={0: 'amount'})
df.insert(0, 'year', 2021)
df

                                                                                      year  \
id_SubFed result                                             period
0         соответствуют замещаемой должности                 АППГ                     2021
                                                             с начала отчетного года  2021
          соответствуют замещаемой должности и рекомендов... АППГ                     2021
                                                             с начала отчетного года  2021
          соответствуют замещаемой должности при условии ... АППГ                     2021
...                                                                                    ...
13        соответствуют замещаемой должности и рекомендов... с начала отчетного года  2021
          соответствуют замещаемой должности при условии ... АППГ                     2021
                                                             с начала отчетного года  2021
          не соответствуют замещаемой должности              АППГ                     2021
                                                             с начала отчетного года  2021

                                                                                     amount
id_SubFed result                                             period
0         соответствуют замещаемой должности                 АППГ                       234
                                                             с начала отчетного года    423
          соответствуют замещаемой должности и рекомендов... АППГ                       195
                                                             с начала отчетного года    124
          соответствуют замещаемой должности при условии ... АППГ                         3
...                                                                                     ...
13        соответствуют замещаемой должности и рекомендов... с начала отчетного года    123
          соответствуют замещаемой должности при условии ... АППГ                         0
                                                             с начала отчетного года      0
          не соответствуют замещаемой должности              АППГ                         0
                                                             с начала отчетного года      0

[112 rows x 2 columns]

In [111]:
#Ranks
appointmentReason = [
    'присвоен классный чин, без сдачи квалификационного экзамена',
    'присвоен классный чин, по результатам квалификационного экзамена',
    'ранее срока, установленного для прохождения службы в предыдущем классном чине'
]
period = [
    'АППГ',
    'с начала отчетного года'
]

df = pd.read_excel('2021x.xlsx', sheet_name='15. Чины', header=None)
df = df.iloc[6:20, 6:17]
df = df.drop([7,9,11,13,15], axis=1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, appointmentReason, period], names=['id_SubFed', 'appointmentReason', 'period'])
df = df.set_axis(m_id, axis=0)
df = df.rename(columns={0: 'amount'})
df.insert(0, 'year', 2021)

In [120]:
#TargetedTraining
categoty = [
    'Количество граждан, заключивших договор о целевом обучении',
    'Количество граждан, получивших профессиональное образование в соответствии с договором о целевом обучении',
    'Количество граждан, поступивших на государственную службу в соответствии с договором о целевом обучении'
]
period = [
    'АППГ',
    'с начала отчетного года'
]

df = pd.read_excel('2021x.xlsx', sheet_name='16. Целевое обучение', header=None)
df = df.iloc[5:19, 2:9]
df = df.drop([7], axis=1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, categoty, period], names=['id_SubFed', 'categoty', 'period'])
df = df.set_axis(m_id, axis=0)
df = df.rename(columns={0: 'amount'})
df.insert(0, 'year', 2021)

In [19]:
#ProfDev_amount
categoty = [
    'решения представителя нанимателя',
    'по результатам аттестации',
    'назначения на иную должность при сокращении должностей или упразднения государственного органа',
    'назначения в порядке должностного роста впервые на должность категории "руководители" или "специалисты"',
    'поступления гражданина на службу впервые'
]

df = pd.read_excel('data_xlsx/2021_ul.xlsx', sheet_name='17.1. Профразвитие', header=None)
df = df.iloc[6:20, 4:9]
df = df.dropna(how='any')
if (df.size == 0): return df
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, categoty], names=['id_SubFed', 'categoty'])
df = df.set_axis(m_id, axis=0)
df = df.rename(columns={0: 'amount'})
df.insert(0, 'year', 2021)
return df

SyntaxError: 'return' outside function (521442754.py, line 13)

In [146]:
#ProfDev_resources
resources = [
    'Государственного заказа',
    'Государственного задания',
    'Средств государственного органа'
]
res_type = [
    'Объём финансирования (тыс. руб.)',
    'Количество служащих'
]
value_type = [
    'план',
    'факт'
]   

df = pd.read_excel('2021x.xlsx', sheet_name='17.2. Профразвитие', header=None)
df = df.iloc[7:21, 2:14]
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, resources, res_type, value_type], names=['id_SubFed', 'resources', 'res_type', 'value_type'])
df = df.set_axis(m_id, axis=0)
df = df.rename(columns={0: 'value'})
df.insert(0, 'year', 2021)

In [21]:
#DPO_GS
DPO = [
    'Профессиональная переподготовка',
    'Повышение квалификации'
]
value_type = [
    'Количество служащих',
    'Объём финансирования (тыс. руб.)'
]
value_name = [
    'план',
    'факт'
]   

file = pd.read_excel('data_xlsx/2020_full.xlsx', sheet_name='17.3. ДПО ГС', header=None)

df = file
df = df.iloc[6:20, 4:20]
df = df.drop([6, 7, 8, 9, 14, 15, 16, 17], axis=1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, DPO, value_type, value_name], names=['id_SubFed', 'DPO', 'value_type', 'value_name'])
df = df.set_axis(m_id, axis=0)
df = df.rename(columns={0: 'value'})
df.insert(0, 'year', 2021)

value_type = [
    'Количество служащих'
]
value_name = [
    'на основании государственных образовательных сертификатов ',
    'за счет собственных средств',
    'прошедших обучение в дистанционной форме'
]   
df1 = file
df1 = df1.iloc[6:20, 7:18]
df1 = df1.drop([10, 11, 12, 13, 14], axis=1)
df1 = df1.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, DPO, value_type, value_name], names=['id_SubFed', 'DPO', 'value_type', 'value_name'])
df1 = df1.set_axis(m_id, axis=0)
df1 = df1.rename(columns={0: 'value'})
df1.insert(0, 'year', 2021)

result = pd.concat([df, df1], axis=0)
result

                                                                                                                               year  \
id_SubFed DPO                             value_type                       value_name
0         Профессиональная переподготовка Количество служащих              план                                                2021
                                                                           факт                                                2021
                                          Объём финансирования (тыс. руб.) план                                                2021
                                                                           факт                                                2021
          Повышение квалификации          Количество служащих              план                                                2021
...                                                                                                                             ...
13        Профессиональная переподготовка Количество служащих              за счет собственных средств                         2021
                                                                           прошедших обучение в дистанционной форме            2021
          Повышение квалификации          Количество служащих              на основании государственных образовательных се...  2021
                                                                           за счет собственных средств                         2021
                                                                           прошедших обучение в дистанционной форме            2021

                                                                                                                                value
id_SubFed DPO                             value_type                       value_name
0         Профессиональная переподготовка Количество служащих              план                                                    61
                                                                           факт                                                    60
                                          Объём финансирования (тыс. руб.) план                                                1073.7
                                                                           факт                                                1073.7
          Повышение квалификации          Количество служащих              план                                                  2061
...                                                                                                                               ...
13        Профессиональная переподготовка Количество служащих              за счет собственных средств                              0
                                                                           прошедших обучение в дистанционной форме                 8
          Повышение квалификации          Количество служащих              на основании государственных образовательных се...       0
                                                                           за счет собственных средств                              1
                                                                           прошедших обучение в дистанционной форме               358

[196 rows x 2 columns]

In [36]:
#DPO_GS_other
DPO_type = [
    'мероприятия, направленные на получение новых знаний, умений',
    'мероприятия, направленные на обмен опытом'
]
value_type = [
    'план',
    'факт'
]   
file = pd.read_excel('data_xlsx/2021x.xlsx', sheet_name='17.4. ДПО ГС', header=None)
df = file
df = df.iloc[7:21, 4:8]
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, DPO_type, value_type], names=['id_SubFed', 'DPO_type', 'value_type'])
df = df.set_axis(m_id, axis=0)
df = df.rename(columns={0: 'value'})
df.insert(0, 'year', 2021)

DPO_type = [
    'служебные стажировки',
    'самообразование'
]
value_type = [
    'факт'
]  
df1 = file
df1 = df1.iloc[7:21, 8:10]
df1 = df1.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, DPO_type, value_type], names=['id_SubFed', 'DPO_type', 'value_type'])
df1 = df1.set_axis(m_id, axis=0)
df1 = df1.rename(columns={0: 'value'})
df1.insert(0, 'year', 2021)

result = pd.concat([df, df1], axis=0)

DPO_type = [
    'Объём финансирования, тыс.руб.'
]
value_type = [
    'план',
    'факт'
] 
df2 = file
df2 = df2.iloc[7:21, 10:12]
df2 = df2.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, DPO_type, value_type], names=['id_SubFed', 'DPO_type', 'value_type'])
df2 = df2.set_axis(m_id, axis=0)
df2 = df2.rename(columns={0: 'value'})
df2.insert(0, 'year', 2021)

result = pd.concat([result, df2], axis=0)

In [42]:
#DPO_MS
DPO_type = [
    'Профессиональная переподготовка',
    'Повышение квалификации',
    'иные образовательные программы'
]  

df = pd.read_excel('data_xlsx/2021x.xlsx', sheet_name='18. ДПО МС', header=None)
df = df.iloc[5:19, 4:9]
df = df.drop([5, 7], axis=1)
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, DPO_type], names=['id_SubFed', 'DPO_type'])
df = df.set_axis(m_id, axis=0)
df = df.rename(columns={0: 'value'})
df.insert(0, 'year', 2021)

In [52]:
#Subsidy ЭТО НАМ НЕ НАДО
category = [
    'Количество гражданских служащих, получивших субсидию',
    'Количество денежных средств выделенных на предоставление единовременной субсидии на приобретение жилого помещения гражданским служащим, руб.'
]
period = [
    'Всего',
    'с начала отчетного года'
]

df = pd.read_excel('data_xlsx/2021x.xlsx', sheet_name='19. Субсидия', header=None)
df = df.iloc[5:19, 2:6]
df = df.stack().reset_index(drop=True).to_frame()
m_id = pd.MultiIndex.from_product([id_SubFed, category, period], names=['id_SubFed', 'category', 'period'])
df = df.set_axis(m_id, axis=0)
df = df.rename(columns={0: 'value'})
df.insert(0, 'year', 2021)